version: '2'
services:
  dev:
    build: .
    command: npm run dev
    volumes:
      - ./:/app
    ports:
      - 5431:5431

  server:
    build: .
    command: npm run server
    volumes:
      - ./:/app
    ports:
      - 3000:3000
