version: '2'
services:
  dev:
    build: .
    command: npm run dev
    volumes:
      - ./:/app
    ports:
      - 5431:5431

  server:
    build: .
    command: npm run server
    links:
      - db
    volumes:
      - ./:/app
    ports:
      - 3000:3000

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=collagr
